config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :items do
    resources :tags
  end

  resources :items do
    resources :reviews
  end

  resources :users do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authorize
    if !current_user
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to '/'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @items = Item.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show
    @item = Item.find(params[:id])
    @review = @item.reviews.new()
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorize, only: [:create]

  def create
    @item = Item.find(params[:item_id])
    @review = @item.reviews.create(review_params)
    @item.save

    redirect_to item_path(@item)
  end

private

  def review_params
    params.require(:review).permit(:body, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_controller_helper.rb
module HomeControllerHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1> We have things for sale!</h1>
<ul>
  <% @items.each do |item| %>
    <li><b><%= link_to(item.name, item_path(item))%></b>, <i>$<%= item.price.to_i %></i></li>
  <% end %>
</ul>

app/views/items/show.html.erb
<h1>Product Details</h1>

<h3><b><%= @item.name %></b>, <i>$<%= @item.price.to_i %></i></h3>

<% if @item.reviews %>
  <% @item.reviews.each do |review| %>
    <h4> <%= review.body %> </h4>
  <% end %>
<% end %>
<br>
<% if current_user %>
  <hr>
  <br>
  <h3>Leave a review:</h3>
  <%= form_for @review, url: item_reviews_path(@item) do |f| %>
    <%= f.hidden_field :item_id, value: @item.id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.text_area :body %><br>
    <%= f.submit %>
  <% end %>
<% end %>
<%#= render @item.reviews %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NounStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="/">Store</a>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <% if current_user %>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %><li>
              <% else %>
                <li><%= link_to "Sign In", new_user_session_path %></li>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>